config/routes.rb
Rails.application.routes.draw do

  post 'workshops/add_person'
  get 'workshops/search_person'
  
get 'workshops/generate_xl_sheet'
post 'workshops/create_xl'

  resources :workshops
  resources :users
  root :to => 'home#index'
  resources :registrations

   get 'prints/registration_card_print'
   get 'prints/income_certificate_print'
   get 'prints/community_certificate_print'
   get 'prints/disability_certificate_print'
   get 'print_preview/registration_card_print'
   get 'print_preview/income_certificate_print'
   get 'print_preview/community_certificate_print'
   get 'print_preview/disability_certificate_print'

get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/models/workshop.rb
class Workshop < ActiveRecord::Base
	belongs_to :registration_form

end

app/controllers/workshops_controller.rb
class WorkshopsController < ApplicationController
def new
		 #binding.pry
		@person = RegistrationForm.find_by(name: params[:name], father_or_husband_name: params[:father_or_husband_name])
	end
	def create
		#binding.pry
		@person = RegistrationForm.find(params[:id])
		unless Workshop.find_by(:registration_form_id=> @person.id).present?
		  workshop = Workshop.create(registration_form_id: @person.id, date_of_issue: params[:date_of_issue],no_of_item: params[:no_of_item],actual_cost: params[:actual_cost],total_assistance_amount: params[:total_assistance_amount])
		end
		redirect_to workshops_search_person_path
	end
	def search_person
	end
	def create_xl
       #binding.pry
       from_date= DateTime.parse(params[:from_date])
       to_date= DateTime.parse(params[:to_date])
       #binding.pry
       @workshop= Workshop.where(date_of_issue: from_date .. to_date)
       CSV.open("workshop.xlsx", "wb") do |csv|
          csv << ["S.NO","Order No","Name","Age","Sex","Address & Mobile Number","Income","Aids/Appliances","Date of Issue","No.of Item","Actual Cost","Total Assistance Amount","Category"]
          sno=1
          @workshop.each do |workshop|
            address = workshop.registration_form.name + "," + workshop.registration_form.street + "," + workshop.registration_form.taluk + "," + workshop.registration_form.district + "," + workshop.registration_form.state + "," + workshop.registration_form.pincode.to_s + "," + (workshop.registration_form.mobile_no.to_s)
  
            csv << [sno,workshop.registration_form.registration_no,workshop.registration_form.name,workshop.registration_form.age,workshop.registration_form.sex,address,workshop.registration_form.monthly_income,workshop.registration_form.aids_or_appliances,workshop.date_of_issue,workshop.no_of_item,workshop.actual_cost,workshop.total_assistance_amount,workshop.registration_form.caste]
            sno += 1
          end
      end
      redirect_to workshops_search_person_path
end


	def generate_xl_sheet
		
    end
  def add_person
  	binding.pry
  	@person = RegistrationForm.find(name: params[:name], father_or_husband_name: params[:father_or_husband_name])
     if @person.present?
     	redirect_to new_workshop_path(@person.id)
     else
     	redirect_to workshop_search_person_path
     end
  end

end

app/helpers/workshop_helper.rb
module WorkshopHelper
end

app/helpers/workshops_helper.rb
module WorkshopsHelper
end

app/views/workshops/generate_xl_sheet.html.erb
<h2>GENERATE XL SHEET</h2>
<%= form_tag workshops_create_xl_path do %>
From_date_of_issue: <%= date_field_tag :from_date %></br>
to_date_of_issue:  <%= date_field_tag :to_date %>
<%= submit_tag "Submit" %>
<% end %>

app/views/workshops/new.html.erb
<h1> workshop Division </h1>


Name: <%= text_field_tag :name, params[:name],:value=> @person.name, :disabled=> "disabled" %>
Age: <%= text_field_tag :age, params[:age],:value=> @person.age, :disabled=> "disabled" %>
Sex: <%= text_field_tag :sex, params[:sex],:value=> @person.sex, :disabled=> "disabled" %>
<% address = @person.hno+","+@person.street+","+@person.town_or_village_or_city+","+@person.taluk+","+@person.district+","+@person.state+","+@person.pincode.to_s+","+@person.mobile_no.to_s %> 
Address: <%= text_field_tag :address, params[:address],:value=> address, :disabled=> "disabled" %>
income: <%= text_field_tag :monthly_income, params[:monthly_income],:value=> ""Rs. "+@person.monthly_income.to_s+"/- p.m"", :disabled=> "disabled" %>

</br>
<%= form_tag '/workshops' do %> 
Date of Issue: <%= date_field_tag :date_of_issue %>
No.of Item: <%= text_field_tag :no_of_item %>
Actual cost <%= text_field_tag :actual_cost %>
Total Assistance Amount :<%= text_field_tag :total_assistance_amount %></br>
<%= hidden_field_tag :id, @person.id %>
<%= submit_tag "Submit", class: 'btn btn-primary' %>
<% end %>

app/views/workshops/search_person.html.erb
<h1>WORK SHOP DIVISION </h1>

<%= form_tag new_workshop_path, :method => 'get' do %>
Name : <%= text_field_tag :name %></br>

S/o,D/o,W/ <%= text_field_tag :father_or_husband_name %></br>

<%= submit_tag "Search", :name => nil %>

<% end %>

<%= link_to "Generate xl sheet",workshops_generate_xl_sheet_path %>

<%= link_to "Back", root_path %>