config/routes.rb
Rails.application.routes.draw do

  post 'workshops/add_person'
  get 'workshops/search_person'
  
get 'workshops/generate_xl_sheet'
post 'workshops/create_xl'

  resources :workshops
  resources :users
  root :to => 'home#index'
  resources :registrations

   get 'prints/registration_card_print'
   get 'prints/income_certificate_print'
   get 'prints/community_certificate_print'
   get 'prints/disability_certificate_print'
   get 'print_preview/registration_card_print'
   get 'print_preview/income_certificate_print'
   get 'print_preview/community_certificate_print'
   get 'print_preview/disability_certificate_print'

get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

end

app/controllers/prints_controller.rb
class PrintsController < ApplicationController

	def registration_card_print
		
	end

	def income_certificate_print
	end

	def community_certificate_print
	end

	def disability_certificate_print
	end

end

app/helpers/prints_helper.rb
module PrintsHelper
end

app/views/prints/community_certificate_print.html.erb
<h1>SELF DECLARATION OF COMMUNITY CERTIFICATE </h1>

<%= form_tag print_preview_community_certificate_print_path, :method => 'get' do %>
Name : <%= text_field_tag :name %></br>

S/o,D/o,W/ <%= text_field_tag :father_or_husband_name %></br>

<%= submit_tag "Search", :name => nil %>

<% end %>

<%= link_to "Back", root_path %>

app/views/prints/disability_certificate_print.html.erb
<h1>DISABILITY CERTIFICATE </h1>

<%= form_tag print_preview_disability_certificate_print_path, :method => 'get' do %>
Name : <%= text_field_tag :name %></br>

S/o,D/o,W/ <%= text_field_tag :father_or_husband_name %></br>

<%= submit_tag "Search", :name => nil %>

<% end %>
<%= link_to "Back", root_path %>

app/views/prints/income_certificate_print.html.erb
<h1>INCOME CERTIFICATE </h1>

<%= form_tag print_preview_income_certificate_print_path, :method => 'get' do %>
Name : <%= text_field_tag :name %></br>

S/o,D/o,W/ <%= text_field_tag :father_or_husband_name %></br>
<%= submit_tag "Search", :name => nil %>

<% end %>
<%= link_to "Back", root_path %>

app/views/prints/registration_card_print.html.erb
<h1>REGISTRATION CARD </h1>

<%= form_tag print_preview_registration_card_print_path, :method => 'get' do %>
Name : <%= text_field_tag :name %></br>

S/o,D/o,W/ <%= text_field_tag :father_or_husband_name %></br>
<%= submit_tag "Search", :name => nil %>

<% end %>

<%= link_to "Back", root_path %>